FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o rest-server ./cmd/rest-server

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/rest-server .

RUN mkdir -p /app/data

EXPOSE 8080

CMD ["./rest-server"] 